version: '1'
services:
  webapp:
    container_name: reimbursement
    build: .
    ports:
      - "8000:8000"
    restart: unless-stop
    depends_on:
      - mongodb
    # links:
    #   - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
