version: "1"
services:
  webapp:
    container_name: reimbursement
    env_file: .env
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - mongodb
    volumes:
      - .:/reimbursement
    # links:
    #   - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
