version: "1"
services:
  webapp:
    # container_name: reimbursement
    environment:
      - db=${db}
    build: .
    restart: on-failure
    depends_on:
      - mongodb
    volumes:
      - .:/reimbursement
    # links:
    #   - mongodb
    # replicas: 2
    ports:
      - "9000-9001:8000"
  mongodb:
    image: mongo

  nginx:
    image: nginx:latest
    ports:
      - "8000:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
