name: Deploy Next.js to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

jobs:
  install_dependencies_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # use node 16
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn build
      # save the build to a tar file
      - run: tar -czf build.tar.gz .next
      # copy the tar file to the server
      - uses: appleboy/scp-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: build.tar.gz
          target: /root/Reimbursement
      # extract the tar file on the server
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/Reimbursement
            tar -xzf build.tar.gz
            rm build.tar.gz
            yarn install --production
            pm2 restart frontend-reimburse
